import { Profile } from 'mixly';

const pins = {};

pins["元控青春"] = {
    description: "MicroPython[ESP32C3 MixGo CE]",
    digital_pin: Profile.generate(['0-18', '21', '33-48']),
    input_pin: Profile.generate(['0-18', '21', '33-48']),
    output_pin: Profile.generate(['0-18', '21', '33-48']),
    pwm_input: Profile.generate(['0-18', '21', '33-48'], 'pwm', 'pwm'),
    analog_input: Profile.generate(['1-18'], 'adc', 'adc'),
    pwm_output: Profile.generate(['0-18', '21', '33-48'], 'pwm', 'pwm'),
    analog_output: Profile.generate(['1-18'], 'adc', 'adc'),
    espnow_channel: Profile.generate(['1-13']),
    haskylens_model: Profile.generate(['0-4']),
    digital: Profile.generate(['0-18', '21', '33-48'], 'pin', 'pin'),
    pwm_pin: Profile.generate(['0-18', '21', '33-48']),
    pwm: Profile.generate(['0-18', '21', '33-48'], 'pwm', 'pwm'),
    analog_pin: Profile.generate(['1-18']),
    analog: Profile.generate(['1-18'], 'adc', 'adc'),
    touch: Profile.generate(['1-14'], 'tc', 'tc'),
    touch_pin: Profile.generate(['1-14']),
    button: [["B1", "B1key"], ["B2", "B2key"], ["A1", "A1key"], ["A2", "A2key"], ["A3", "A3key"], ["A4", "A4key"]],
    buttonB: [["B1", "B1key"], ["B2", "B2key"]],
    axis: Profile.generate(['0-4']),
    exlcdh: Profile.generate(['0-15']),
    exlcdv: Profile.generate(['0-7']),
    brightness: Profile.generate(['0-9']),
    tts_voice: Profile.generate(['0-16']),
    tts_builtin_music: Profile.generate(['0-47']),
    tts_bgmusic: Profile.generate(['0-15']),
    builtinimg: [
        ["Heart", "expression_picture.Heart"],
        ["Angry", "expression_picture.Angry"],
        ["Bored", "expression_picture.Bored"],
        ["Confused", "expression_picture.Confused"],
        ["Happy", "expression_picture.Happy"],
        ["Paper", "expression_picture.Paper"],
        ["Rock", "expression_picture.Rock"],
        ["Sad", "expression_picture.Sad"],
        ["Scissors", "expression_picture.Scissors"],
        ["Silly", "expression_picture.Silly"],
        ["Sleep", "expression_picture.Sleep"],
        ["Small_heart", "expression_picture.Small_heart"],
        ["Small_paper", "expression_picture.Small_paper"],
        ["Small_rock", "expression_picture.Small_rock"],
        ["Small_scissors", "expression_picture.Small_scissors"],
        ["Smile", "expression_picture.Smile"],
        ["Surprise", "expression_picture.Surprise"],
        ["Wonderful", "expression_picture.Wonderful"],
        ["Eyes_Angry", "eye_picture.Eyes_Angry"],
        ["Awake", "eye_picture.Awake"],
        ["Black_eye", "eye_picture.Black_eye"],
        ["Bottom_left", "eye_picture.Bottom_left"],
        ["Bottom_right", "eye_picture.Bottom_right"],
        ["Crazy_1", "eye_picture.Crazy_1"],
        ["Crazy_2", "eye_picture.Crazy_2"],
        ["Disappointed", "eye_picture.Disappointed"],
        ["Dizzy", "eye_picture.Dizzy"],
        ["Down", "eye_picture.Down"],
        ["Evil", "eye_picture.Evil"],
        ["Hurt", "eye_picture.Hurt"],
        ["Knocked_out", "eye_picture.Knocked_out"],
        ["Love", "eye_picture.Love"],
        ["Middle_left", "eye_picture.Middle_left"],
        ["Middle_right", "eye_picture.Middle_right"],
        ["Neutral", "eye_picture.Neutral"],
        ["Nuclear", "eye_picture.Nuclear"],
        ["Pinch_left", "eye_picture.Pinch_left"],
        ["Pinch_middle", "eye_picture.Pinch_middle"],
        ["Pinch_right", "eye_picture.Pinch_right"],
        ["Tear", "eye_picture.Tear"],
        ["Tired_left", "eye_picture.Tired_left"],
        ["Tired_middle", "eye_picture.Tired_middle"],
        ["Tired_right", "eye_picture.Tired_right"],
        ["Toxic", "eye_picture.Toxic"],
        ["Up", "eye_picture.Up"],
        ["Winking", "eye_picture.Winking"],
        ["Accept", "informatio_picture.Accept"],
        ["Backward", "informatio_picture.Backward"],
        ["Decline", "informatio_picture.Decline"],
        ["Forward", "informatio_picture.Forward"],
        ["Left", "informatio_picture.Left"],
        ["No_go", "informatio_picture.No_go"],
        ["Question_mark", "informatio_picture.Question_mark"],
        ["Right", "informatio_picture.Right"],
        ["Stop_1", "informatio_picture.Stop_1"],
        ["Stop_2", "informatio_picture.Stop_2"],
        ["Thumbs_down", "informatio_picture.Thumbs_down"],
        ["Thumbs_up", "informatio_picture.Thumbs_up"],
        ["Warning", "informatio_picture.Warning"],
        ["Bomb", "object_picture.Bomb"],
        ["Boom", "object_picture.Boom"],
        ["Fire", "object_picture.Fire"],
        ["Flowers", "object_picture.Flowers"],
        ["Forest", "object_picture.Forest"],
        ["Lightning", "object_picture.Lightning"],
        ["Light_off", "object_picture.Light_off"],
        ["Light_on", "object_picture.Light_on"],
        ["Night", "object_picture.Night"],
        ["Pirate", "object_picture.Pirate"],
        ["Snow", "object_picture.Snow"],
        ["Target", "object_picture.Target"],
        ["Bar_0", "progres_picture.Bar_0"],
        ["Bar_1", "progres_picture.Bar_1"],
        ["Bar_2", "progres_picture.Bar_2"],
        ["Bar_3", "progres_picture.Bar_3"],
        ["Bar_4", "progres_picture.Bar_4"],
        ["Dial_0", "progres_picture.Dial_0"],
        ["Dial_1", "progres_picture.Dial_1"],
        ["Dial_2", "progres_picture.Dial_2"],
        ["Dial_3", "progres_picture.Dial_3"],
        ["Dial_4", "progres_picture.Dial_4"],
        ["Dots_0", "progres_picture.Dots_0"],
        ["Dots_1", "progres_picture.Dots_1"],
        ["Dots_2", "progres_picture.Dots_2"],
        ["Dots_3", "progres_picture.Dots_3"],
        ["Hourglass_0", "progres_picture.Hourglass_0"],
        ["Hourglass_1", "progres_picture.Hourglass_1"],
        ["Hourglass_2", "progres_picture.Hourglass_2"],
        ["Timer_0", "progres_picture.Timer_0"],
        ["Timer_1", "progres_picture.Timer_1"],
        ["Timer_2", "progres_picture.Timer_2"],
        ["Timer_3", "progres_picture.Timer_3"],
        ["Timer_4", "progres_picture.Timer_4"],
        ["Water_level_0", "progres_picture.Water_level_0"],
        ["Water_level_1", "progres_picture.Water_level_1"],
        ["Water_level_2", "progres_picture.Water_level_2"],
        ["Water_level_3", "progres_picture.Water_level_3"]
    ],
    builtinimg_extern: [["HEART", "matrix32x12.Matrix.HEART"], ["HEART_SMALL", "matrix32x12.Matrix.HEART_SMALL"], ["HAPPY", "matrix32x12.Matrix.HAPPY"], ["SAD", "matrix32x12.Matrix.SAD"], ["SMILE", "matrix32x12.Matrix.SMILE"], ["SILLY", "matrix32x12.Matrix.SILLY"], ["FABULOUS", "matrix32x12.Matrix.FABULOUS"], ["SURPRISED", "matrix32x12.Matrix.SURPRISED"], ["ASLEEP", "matrix32x12.Matrix.ASLEEP"], ["ANGRY", "matrix32x12.Matrix.ANGRY"], ["CONFUSED", "matrix32x12.Matrix.CONFUSED"], ["NO", "matrix32x12.Matrix.NO"], ["YES", "matrix32x12.Matrix.YES"], ["LEFT_ARROW", "matrix32x12.Matrix.LEFT_ARROW"], ["RIGHT_ARROW", "matrix32x12.Matrix.RIGHT_ARROW"], ["DRESS", "matrix32x12.Matrix.DRESS"], ["TRANSFORMERS", "matrix32x12.Matrix.TRANSFORMERS"], ["SCISSORS", "matrix32x12.Matrix.SCISSORS"], ["EXIT", "matrix32x12.Matrix.EXIT"], ["TREE", "matrix32x12.Matrix.TREE"], ["PACMAN", "matrix32x12.Matrix.PACMAN"], ["TARGET", "matrix32x12.Matrix.TARGET"], ["TSHIRT", "matrix32x12.Matrix.TSHIRT"], ["ROLLERSKATE", "matrix32x12.Matrix.ROLLERSKATE"], ["DUCK", "matrix32x12.Matrix.DUCK"], ["HOUSE", "matrix32x12.Matrix.HOUSE"], ["TORTOISE", "matrix32x12.Matrix.TORTOISE"], ["BUTTERFLY", "matrix32x12.Matrix.BUTTERFLY"], ["STICKFIGURE", "matrix32x12.Matrix.STICKFIGURE"], ["GHOST", "matrix32x12.Matrix.GHOST"], ["PITCHFORK", "matrix32x12.Matrix.PITCHFORK"], ["onboard_music_QUAVERS", "matrix32x12.Matrix.onboard_music_QUAVERS"], ["onboard_music_QUAVER", "matrix32x12.Matrix.onboard_music_QUAVER"], ["onboard_music_CROTCHET", "matrix32x12.Matrix.onboard_music_CROTCHET"], ["COW", "matrix32x12.Matrix.COW"], ["RABBIT", "matrix32x12.Matrix.RABBIT"], ["SQUARE_SMALL", "matrix32x12.Matrix.SQUARE_SMALL"], ["SQUARE", "matrix32x12.Matrix.SQUARE"], ["DIAMOND_SMALL", "matrix32x12.Matrix.DIAMOND_SMALL"], ["DIAMOND", "matrix32x12.Matrix.DIAMOND"], ["CHESSBOARD", "matrix32x12.Matrix.CHESSBOARD"], ["TRIANGLE_LEFT", "matrix32x12.Matrix.TRIANGLE_LEFT"], ["TRIANGLE", "matrix32x12.Matrix.TRIANGLE"], ["SNAKE", "matrix32x12.Matrix.SNAKE"], ["UMBRELLA", "matrix32x12.Matrix.UMBRELLA"], ["SKULL", "matrix32x12.Matrix.SKULL"], ["GIRAFFE", "matrix32x12.Matrix.GIRAFFE"], ["SWORD", "matrix32x12.Matrix.SWORD"]],
    imglist: [["ALL_CLOCKS", "matrix.Image.ALL_CLOCKS"], ["ALL_ARROWS", "matrix.Image.ALL_ARROWS"]],
    playlist: [["DADADADUM", "spk_midi.DADADADUM"], ["ENTERTAINER", "spk_midi.ENTERTAINER"], ["PRELUDE", "spk_midi.PRELUDE"], ["ODE", "spk_midi.ODE"], ["NYAN", "spk_midi.NYAN"], ["RINGTONE", "spk_midi.RINGTONE"], ["FUNK", "spk_midi.FUNK"], ["BLUES", "spk_midi.BLUES"], ["BIRTHDAY", "spk_midi.BIRTHDAY"], ["WEDDING", "spk_midi.WEDDING"], ["FUNERAL", "spk_midi.FUNERAL"], ["PUNCHLINE", "spk_midi.PUNCHLINE"], ["PYTHON", "spk_midi.PYTHON"], ["BADDY", "spk_midi.BADDY"], ["CHASE", "spk_midi.CHASE"], ["BA_DING", "spk_midi.BA_DING"], ["WAWAWAWAA", "spk_midi.WAWAWAWAA"], ["JUMP_UP", "spk_midi.JUMP_UP"], ["JUMP_DOWN", "spk_midi.JUMP_DOWN"], ["POWER_UP", "spk_midi.POWER_UP"], ["POWER_DOWN", "spk_midi.POWER_DOWN"]],
    playlist_extern: [["DADADADUM", "DADADADUM"], ["ENTERTAINER", "ENTERTAINER"], ["PRELUDE", "PRELUDE"], ["ODE", "ODE"], ["NYAN", "NYAN"], ["RINGTONE", "RINGTONE"], ["FUNK", "FUNK"], ["BLUES", "BLUES"], ["BIRTHDAY", "BIRTHDAY"], ["WEDDING", "WEDDING"], ["FUNERAL", "FUNERAL"], ["PUNCHLINE", "PUNCHLINE"], ["PYTHON", "PYTHON"], ["BADDY", "BADDY"], ["CHASE", "CHASE"], ["BA_DING", "BA_DING"], ["WAWAWAWAA", "WAWAWAWAA"], ["JUMP_UP", "JUMP_UP"], ["JUMP_DOWN", "JUMP_DOWN"], ["POWER_UP", "POWER_UP"], ["POWER_DOWN", "POWER_DOWN"]],
    tone_notes: [
        ["NOTE_C3", "131"], ["NOTE_D3", "147"], ["NOTE_E3", "165"], ["NOTE_F3", "175"], ["NOTE_G3", "196"], ["NOTE_A3", "220"], ["NOTE_B3", "247"],
        ["NOTE_C4", "262"], ["NOTE_D4", "294"], ["NOTE_E4", "330"], ["NOTE_F4", "349"], ["NOTE_G4", "392"], ["NOTE_A4", "440"], ["NOTE_B4", "494"],
        ["NOTE_C5", "523"], ["NOTE_D5", "587"], ["NOTE_E5", "659"], ["NOTE_F5", "698"], ["NOTE_G5", "784"], ["NOTE_A5", "880"], ["NOTE_B5", "988"]
    ],
    serial_pin: [["pin0", "0"], ["pin1", "1"], ["pin2", "2"], ["pin8", "8"], ["pin12", "12"], ["pin13", "13"], ["pin14", "14"], ["pin15", "15"], ["pin16", "16"]],
    radio_power: [['0', '0'], ['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5'], ['6', '6'], ['7', '7']],
    radio_datarate: [["1Mbit", "RATE_1MBIT"], ["250Kbit", "RATE_250KBIT"], ["2Mbit", "RATE_2MBIT"]],
    one_more: [["ONE_SHOT", "ONE_SHOT"], ["PERIODIC", "PERIODIC"]],
    digital_dot: [["0", "0"], ["1", "1"], ["2", "2"]],
};

pins["元控自强"] = {
    description: "MicroPython[ESP32C3 MixGo CE]",
    digital_pin: Profile.generate(['0-18', '21', '33-48']),
    input_pin: Profile.generate(['0-18', '21', '33-48']),
    output_pin: Profile.generate(['0-18', '21', '33-48']),
    pwm_input: Profile.generate(['0-18', '21', '33-48'], 'pwm', 'pwm'),
    analog_input: Profile.generate(['1-18'], 'adc', 'adc'),
    pwm_output: Profile.generate(['0-18', '21', '33-48'], 'pwm', 'pwm'),
    analog_output: Profile.generate(['1-18'], 'adc', 'adc'),
    espnow_channel: Profile.generate(['1-13']),
    haskylens_model: Profile.generate(['0-4']),
    digital: Profile.generate(['0-18', '21', '33-48'], 'pin', 'pin'),
    pwm_pin: Profile.generate(['0-18', '21', '33-48']),
    pwm: Profile.generate(['0-18', '21', '33-48'], 'pwm', 'pwm'),
    analog_pin: Profile.generate(['1-18']),
    analog: Profile.generate(['1-18'], 'adc', 'adc'),
    touch: Profile.generate(['1-14'], 'tc', 'tc'),
    touch_pin: Profile.generate(['1-14']),
    button: [["B1", "B1key"], ["B2", "B2key"], ["A1", "A1key"], ["A2", "A2key"], ["A3", "A3key"], ["A4", "A4key"]],
    buttonB: [["B1", "B1key"], ["B2", "B2key"]],
    axis: Profile.generate(['0-4']),
    exlcdh: Profile.generate(['0-15']),
    exlcdv: Profile.generate(['0-7']),
    brightness: Profile.generate(['0-9']),
    tts_voice: Profile.generate(['0-16']),
    tts_builtin_music: Profile.generate(['0-47']),
    tts_bgmusic: Profile.generate(['0-15']),
    builtinimg: pins["元控青春"].builtinimg,
    builtinimg_extern: [["HEART", "matrix32x12.Matrix.HEART"], ["HEART_SMALL", "matrix32x12.Matrix.HEART_SMALL"], ["HAPPY", "matrix32x12.Matrix.HAPPY"], ["SAD", "matrix32x12.Matrix.SAD"], ["SMILE", "matrix32x12.Matrix.SMILE"], ["SILLY", "matrix32x12.Matrix.SILLY"], ["FABULOUS", "matrix32x12.Matrix.FABULOUS"], ["SURPRISED", "matrix32x12.Matrix.SURPRISED"], ["ASLEEP", "matrix32x12.Matrix.ASLEEP"], ["ANGRY", "matrix32x12.Matrix.ANGRY"], ["CONFUSED", "matrix32x12.Matrix.CONFUSED"], ["NO", "matrix32x12.Matrix.NO"], ["YES", "matrix32x12.Matrix.YES"], ["LEFT_ARROW", "matrix32x12.Matrix.LEFT_ARROW"], ["RIGHT_ARROW", "matrix32x12.Matrix.RIGHT_ARROW"], ["DRESS", "matrix32x12.Matrix.DRESS"], ["TRANSFORMERS", "matrix32x12.Matrix.TRANSFORMERS"], ["SCISSORS", "matrix32x12.Matrix.SCISSORS"], ["EXIT", "matrix32x12.Matrix.EXIT"], ["TREE", "matrix32x12.Matrix.TREE"], ["PACMAN", "matrix32x12.Matrix.PACMAN"], ["TARGET", "matrix32x12.Matrix.TARGET"], ["TSHIRT", "matrix32x12.Matrix.TSHIRT"], ["ROLLERSKATE", "matrix32x12.Matrix.ROLLERSKATE"], ["DUCK", "matrix32x12.Matrix.DUCK"], ["HOUSE", "matrix32x12.Matrix.HOUSE"], ["TORTOISE", "matrix32x12.Matrix.TORTOISE"], ["BUTTERFLY", "matrix32x12.Matrix.BUTTERFLY"], ["STICKFIGURE", "matrix32x12.Matrix.STICKFIGURE"], ["GHOST", "matrix32x12.Matrix.GHOST"], ["PITCHFORK", "matrix32x12.Matrix.PITCHFORK"], ["onboard_music_QUAVERS", "matrix32x12.Matrix.onboard_music_QUAVERS"], ["onboard_music_QUAVER", "matrix32x12.Matrix.onboard_music_QUAVER"], ["onboard_music_CROTCHET", "matrix32x12.Matrix.onboard_music_CROTCHET"], ["COW", "matrix32x12.Matrix.COW"], ["RABBIT", "matrix32x12.Matrix.RABBIT"], ["SQUARE_SMALL", "matrix32x12.Matrix.SQUARE_SMALL"], ["SQUARE", "matrix32x12.Matrix.SQUARE"], ["DIAMOND_SMALL", "matrix32x12.Matrix.DIAMOND_SMALL"], ["DIAMOND", "matrix32x12.Matrix.DIAMOND"], ["CHESSBOARD", "matrix32x12.Matrix.CHESSBOARD"], ["TRIANGLE_LEFT", "matrix32x12.Matrix.TRIANGLE_LEFT"], ["TRIANGLE", "matrix32x12.Matrix.TRIANGLE"], ["SNAKE", "matrix32x12.Matrix.SNAKE"], ["UMBRELLA", "matrix32x12.Matrix.UMBRELLA"], ["SKULL", "matrix32x12.Matrix.SKULL"], ["GIRAFFE", "matrix32x12.Matrix.GIRAFFE"], ["SWORD", "matrix32x12.Matrix.SWORD"]],
    imglist: [["ALL_CLOCKS", "matrix.Image.ALL_CLOCKS"], ["ALL_ARROWS", "matrix.Image.ALL_ARROWS"]],
    playlist: [["DADADADUM", "onboard_music.DADADADUM"], ["ENTERTAINER", "onboard_music.ENTERTAINER"], ["PRELUDE", "onboard_music.PRELUDE"], ["ODE", "onboard_music.ODE"], ["NYAN", "onboard_music.NYAN"], ["RINGTONE", "onboard_music.RINGTONE"], ["FUNK", "onboard_music.FUNK"], ["BLUES", "onboard_music.BLUES"], ["BIRTHDAY", "onboard_music.BIRTHDAY"], ["WEDDING", "onboard_music.WEDDING"], ["FUNERAL", "onboard_music.FUNERAL"], ["PUNCHLINE", "onboard_music.PUNCHLINE"], ["PYTHON", "onboard_music.PYTHON"], ["BADDY", "onboard_music.BADDY"], ["CHASE", "onboard_music.CHASE"], ["BA_DING", "onboard_music.BA_DING"], ["WAWAWAWAA", "onboard_music.WAWAWAWAA"], ["JUMP_UP", "onboard_music.JUMP_UP"], ["JUMP_DOWN", "onboard_music.JUMP_DOWN"], ["POWER_UP", "onboard_music.POWER_UP"], ["POWER_DOWN", "onboard_music.POWER_DOWN"]],
    playlist_extern: [["DADADADUM", "DADADADUM"], ["ENTERTAINER", "ENTERTAINER"], ["PRELUDE", "PRELUDE"], ["ODE", "ODE"], ["NYAN", "NYAN"], ["RINGTONE", "RINGTONE"], ["FUNK", "FUNK"], ["BLUES", "BLUES"], ["BIRTHDAY", "BIRTHDAY"], ["WEDDING", "WEDDING"], ["FUNERAL", "FUNERAL"], ["PUNCHLINE", "PUNCHLINE"], ["PYTHON", "PYTHON"], ["BADDY", "BADDY"], ["CHASE", "CHASE"], ["BA_DING", "BA_DING"], ["WAWAWAWAA", "WAWAWAWAA"], ["JUMP_UP", "JUMP_UP"], ["JUMP_DOWN", "JUMP_DOWN"], ["POWER_UP", "POWER_UP"], ["POWER_DOWN", "POWER_DOWN"]],
    tone_notes: [
        ["NOTE_C3", "131"], ["NOTE_D3", "147"], ["NOTE_E3", "165"], ["NOTE_F3", "175"], ["NOTE_G3", "196"], ["NOTE_A3", "220"], ["NOTE_B3", "247"],
        ["NOTE_C4", "262"], ["NOTE_D4", "294"], ["NOTE_E4", "330"], ["NOTE_F4", "349"], ["NOTE_G4", "392"], ["NOTE_A4", "440"], ["NOTE_B4", "494"],
        ["NOTE_C5", "523"], ["NOTE_D5", "587"], ["NOTE_E5", "659"], ["NOTE_F5", "698"], ["NOTE_G5", "784"], ["NOTE_A5", "880"], ["NOTE_B5", "988"]
    ],
    serial_pin: [["pin0", "0"], ["pin1", "1"], ["pin2", "2"], ["pin8", "8"], ["pin12", "12"], ["pin13", "13"], ["pin14", "14"], ["pin15", "15"], ["pin16", "16"]],
    radio_power: [['0', '0'], ['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5'], ['6', '6'], ['7', '7']],
    radio_datarate: [["1Mbit", "RATE_1MBIT"], ["250Kbit", "RATE_250KBIT"], ["2Mbit", "RATE_2MBIT"]],
    one_more: [["ONE_SHOT", "ONE_SHOT"], ["PERIODIC", "PERIODIC"]],
    digital_dot: [["0", "0"], ["1", "1"], ["2", "2"]],
};

pins["ESP32S2 Generic"] = {
    description: "MicroPython[ESP32C3 MixGo CC]",
    digital_pin: Profile.generate(['0-18', '21', '33-48']),
    input_pin: Profile.generate(['0-18', '21', '33-48']),
    output_pin: Profile.generate(['0-18', '21', '33-48']),
    pwm_input: Profile.generate(['0-18', '21', '33-48'], 'pwm', 'pwm'),
    analog_input: Profile.generate(['1-18'], 'adc', 'adc'),
    pwm_output: Profile.generate(['0-18', '21', '33-48'], 'pwm', 'pwm'),
    analog_output: Profile.generate(['1-18'], 'adc', 'adc'),
    espnow_channel: Profile.generate(['1-13']),
    haskylens_model: Profile.generate(['0-4']),
    digital: Profile.generate(['0-18', '21', '33-48'], 'pin', 'pin'),
    pwm_pin: Profile.generate(['0-18', '21', '33-48']),
    pwm: Profile.generate(['0-18', '21', '33-48'], 'pwm', 'pwm'),
    analog_pin: Profile.generate(['1-18']),
    analog: Profile.generate(['1-18'], 'adc', 'adc'),
    touch: Profile.generate(['1-14'], 'tc', 'tc'),
    touch_pin: Profile.generate(['1-14']),
    button: [["B1", "B1key"], ["B2", "B2key"], ["A1", "A1key"], ["A2", "A2key"], ["A3", "A3key"], ["A4", "A4key"]],
    buttonB: [["B1", "B1key"], ["B2", "B2key"]],
    axis: Profile.generate(['0-4']),
    exlcdh: Profile.generate(['0-15']),
    exlcdv: Profile.generate(['0-7']),
    brightness: Profile.generate(['0-9']),
    tts_voice: Profile.generate(['0-16']),
    tts_builtin_music: Profile.generate(['0-47']),
    tts_bgmusic: Profile.generate(['0-15']),
    builtinimg: pins["元控青春"].builtinimg,
    builtinimg_extern: [["HEART", "matrix32x12.Matrix.HEART"], ["HEART_SMALL", "matrix32x12.Matrix.HEART_SMALL"], ["HAPPY", "matrix32x12.Matrix.HAPPY"], ["SAD", "matrix32x12.Matrix.SAD"], ["SMILE", "matrix32x12.Matrix.SMILE"], ["SILLY", "matrix32x12.Matrix.SILLY"], ["FABULOUS", "matrix32x12.Matrix.FABULOUS"], ["SURPRISED", "matrix32x12.Matrix.SURPRISED"], ["ASLEEP", "matrix32x12.Matrix.ASLEEP"], ["ANGRY", "matrix32x12.Matrix.ANGRY"], ["CONFUSED", "matrix32x12.Matrix.CONFUSED"], ["NO", "matrix32x12.Matrix.NO"], ["YES", "matrix32x12.Matrix.YES"], ["LEFT_ARROW", "matrix32x12.Matrix.LEFT_ARROW"], ["RIGHT_ARROW", "matrix32x12.Matrix.RIGHT_ARROW"], ["DRESS", "matrix32x12.Matrix.DRESS"], ["TRANSFORMERS", "matrix32x12.Matrix.TRANSFORMERS"], ["SCISSORS", "matrix32x12.Matrix.SCISSORS"], ["EXIT", "matrix32x12.Matrix.EXIT"], ["TREE", "matrix32x12.Matrix.TREE"], ["PACMAN", "matrix32x12.Matrix.PACMAN"], ["TARGET", "matrix32x12.Matrix.TARGET"], ["TSHIRT", "matrix32x12.Matrix.TSHIRT"], ["ROLLERSKATE", "matrix32x12.Matrix.ROLLERSKATE"], ["DUCK", "matrix32x12.Matrix.DUCK"], ["HOUSE", "matrix32x12.Matrix.HOUSE"], ["TORTOISE", "matrix32x12.Matrix.TORTOISE"], ["BUTTERFLY", "matrix32x12.Matrix.BUTTERFLY"], ["STICKFIGURE", "matrix32x12.Matrix.STICKFIGURE"], ["GHOST", "matrix32x12.Matrix.GHOST"], ["PITCHFORK", "matrix32x12.Matrix.PITCHFORK"], ["onboard_music_QUAVERS", "matrix32x12.Matrix.onboard_music_QUAVERS"], ["onboard_music_QUAVER", "matrix32x12.Matrix.onboard_music_QUAVER"], ["onboard_music_CROTCHET", "matrix32x12.Matrix.onboard_music_CROTCHET"], ["COW", "matrix32x12.Matrix.COW"], ["RABBIT", "matrix32x12.Matrix.RABBIT"], ["SQUARE_SMALL", "matrix32x12.Matrix.SQUARE_SMALL"], ["SQUARE", "matrix32x12.Matrix.SQUARE"], ["DIAMOND_SMALL", "matrix32x12.Matrix.DIAMOND_SMALL"], ["DIAMOND", "matrix32x12.Matrix.DIAMOND"], ["CHESSBOARD", "matrix32x12.Matrix.CHESSBOARD"], ["TRIANGLE_LEFT", "matrix32x12.Matrix.TRIANGLE_LEFT"], ["TRIANGLE", "matrix32x12.Matrix.TRIANGLE"], ["SNAKE", "matrix32x12.Matrix.SNAKE"], ["UMBRELLA", "matrix32x12.Matrix.UMBRELLA"], ["SKULL", "matrix32x12.Matrix.SKULL"], ["GIRAFFE", "matrix32x12.Matrix.GIRAFFE"], ["SWORD", "matrix32x12.Matrix.SWORD"]],
    imglist: [["ALL_CLOCKS", "matrix.Image.ALL_CLOCKS"], ["ALL_ARROWS", "matrix.Image.ALL_ARROWS"]],
    playlist: [["DADADADUM", ".DADADADUM"], ["ENTERTAINER", ".ENTERTAINER"], ["PRELUDE", ".PRELUDE"], ["ODE", ".ODE"], ["NYAN", ".NYAN"], ["RINGTONE", ".RINGTONE"], ["FUNK", ".FUNK"], ["BLUES", ".BLUES"], ["BIRTHDAY", ".BIRTHDAY"], ["WEDDING", ".WEDDING"], ["FUNERAL", ".FUNERAL"], ["PUNCHLINE", ".PUNCHLINE"], ["PYTHON", ".PYTHON"], ["BADDY", ".BADDY"], ["CHASE", ".CHASE"], ["BA_DING", ".BA_DING"], ["WAWAWAWAA", ".WAWAWAWAA"], ["JUMP_UP", ".JUMP_UP"], ["JUMP_DOWN", ".JUMP_DOWN"], ["POWER_UP", ".POWER_UP"], ["POWER_DOWN", ".POWER_DOWN"]],
    playlist_extern: [["DADADADUM", "DADADADUM"], ["ENTERTAINER", "ENTERTAINER"], ["PRELUDE", "PRELUDE"], ["ODE", "ODE"], ["NYAN", "NYAN"], ["RINGTONE", "RINGTONE"], ["FUNK", "FUNK"], ["BLUES", "BLUES"], ["BIRTHDAY", "BIRTHDAY"], ["WEDDING", "WEDDING"], ["FUNERAL", "FUNERAL"], ["PUNCHLINE", "PUNCHLINE"], ["PYTHON", "PYTHON"], ["BADDY", "BADDY"], ["CHASE", "CHASE"], ["BA_DING", "BA_DING"], ["WAWAWAWAA", "WAWAWAWAA"], ["JUMP_UP", "JUMP_UP"], ["JUMP_DOWN", "JUMP_DOWN"], ["POWER_UP", "POWER_UP"], ["POWER_DOWN", "POWER_DOWN"]],
    tone_notes: [
        ["NOTE_C3", "131"], ["NOTE_D3", "147"], ["NOTE_E3", "165"], ["NOTE_F3", "175"], ["NOTE_G3", "196"], ["NOTE_A3", "220"], ["NOTE_B3", "247"],
        ["NOTE_C4", "262"], ["NOTE_D4", "294"], ["NOTE_E4", "330"], ["NOTE_F4", "349"], ["NOTE_G4", "392"], ["NOTE_A4", "440"], ["NOTE_B4", "494"],
        ["NOTE_C5", "523"], ["NOTE_D5", "587"], ["NOTE_E5", "659"], ["NOTE_F5", "698"], ["NOTE_G5", "784"], ["NOTE_A5", "880"], ["NOTE_B5", "988"]
    ],
    serial_pin: [["pin0", "0"], ["pin1", "1"], ["pin2", "2"], ["pin8", "8"], ["pin12", "12"], ["pin13", "13"], ["pin14", "14"], ["pin15", "15"], ["pin16", "16"]],
    radio_power: [['0', '0'], ['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5'], ['6', '6'], ['7', '7']],
    radio_datarate: [["1Mbit", "RATE_1MBIT"], ["250Kbit", "RATE_250KBIT"], ["2Mbit", "RATE_2MBIT"]],
    one_more: [["ONE_SHOT", "ONE_SHOT"], ["PERIODIC", "PERIODIC"]],
    digital_dot: [["0", "0"], ["1", "1"], ["2", "2"]],
};

export default pins;